Rebuilt networking layer to serve API through both  protocols simultaneously: WebSocket & HTTP
Reformat API transfer packet:
- input { type: "call", id: number, method: `${unit}/${method}`,
args: object }
- output { type: "callback", id: number, result: any,
error: { code: number, message: string }}

Fix createRouting function: check for contextualized
API function instead of method in plain object.